// offline_data.js
// Dados estáticos da Bíblia para funcionamento offline e controle de rate limits

const BIBLE_BOOKS = [
  // Antigo Testamento
  { abbrev: "gn", name: "Gênesis", chapters: 50, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "ex", name: "Êxodo", chapters: 40, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "lv", name: "Levítico", chapters: 27, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "nm", name: "Números", chapters: 36, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "dt", name: "Deuteronômio", chapters: 34, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "js", name: "Josué", chapters: 24, author: "Josué", group: "Históricos", testament: "VT" },
  { abbrev: "jz", name: "Juízes", chapters: 21, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "rt", name: "Rute", chapters: 4, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "1sm", name: "1 Samuel", chapters: 31, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "2sm", name: "2 Samuel", chapters: 24, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "1rs", name: "1 Reis", chapters: 22, author: "Jeremias", group: "Históricos", testament: "VT" },
  { abbrev: "2rs", name: "2 Reis", chapters: 25, author: "Jeremias", group: "Históricos", testament: "VT" },
  { abbrev: "1cr", name: "1 Crônicas", chapters: 29, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "2cr", name: "2 Crônicas", chapters: 36, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "ed", name: "Esdras", chapters: 10, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "ne", name: "Neemias", chapters: 13, author: "Neemias", group: "Históricos", testament: "VT" },
  { abbrev: "et", name: "Ester", chapters: 10, author: "Mardoqueu", group: "Históricos", testament: "VT" },
  { abbrev: "job", name: "Jó", chapters: 42, author: "Desconhecido", group: "Poéticos", testament: "VT" },
  { abbrev: "sl", name: "Salmos", chapters: 150, author: "Davi, Asafe, outros", group: "Poéticos", testament: "VT" },
  { abbrev: "pv", name: "Provérbios", chapters: 31, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "ec", name: "Eclesiastes", chapters: 12, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "ct", name: "Cânticos", chapters: 8, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "is", name: "Isaías", chapters: 66, author: "Isaías", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "jr", name: "Jeremias", chapters: 52, author: "Jeremias", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "lm", name: "Lamentações", chapters: 5, author: "Jeremias", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "ez", name: "Ezequiel", chapters: 48, author: "Ezequiel", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "dn", name: "Daniel", chapters: 12, author: "Daniel", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "os", name: "Oseias", chapters: 14, author: "Oseias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "jl", name: "Joel", chapters: 3, author: "Joel", group: "Profetas Menores", testament: "VT" },
  { abbrev: "am", name: "Amós", chapters: 9, author: "Amós", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ob", name: "Obadias", chapters: 1, author: "Obadias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "jn", name: "Jonas", chapters: 4, author: "Jonas", group: "Profetas Menores", testament: "VT" },
  { abbrev: "mq", name: "Miqueias", chapters: 7, author: "Miqueias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "na", name: "Naum", chapters: 3, author: "Naum", group: "Profetas Menores", testament: "VT" },
  { abbrev: "hc", name: "Habacuque", chapters: 3, author: "Habacuque", group: "Profetas Menores", testament: "VT" },
  { abbrev: "sf", name: "Sofonias", chapters: 3, author: "Sofonias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ag", name: "Ageu", chapters: 2, author: "Ageu", group: "Profetas Menores", testament: "VT" },
  { abbrev: "zc", name: "Zacarias", chapters: 14, author: "Zacarias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ml", name: "Malaquias", chapters: 4, author: "Malaquias", group: "Profetas Menores", testament: "VT" },

  // Novo Testamento
  { abbrev: "mt", name: "Mateus", chapters: 28, author: "Mateus", group: "Evangelhos", testament: "NT" },
  { abbrev: "mc", name: "Marcos", chapters: 16, author: "Marcos", group: "Evangelhos", testament: "NT" },
  { abbrev: "lc", name: "Lucas", chapters: 24, author: "Lucas", group: "Evangelhos", testament: "NT" },
  { abbrev: "jo", name: "João", chapters: 21, author: "João", group: "Evangelhos", testament: "NT" },
  { abbrev: "at", name: "Atos", chapters: 28, author: "Lucas", group: "Histórico", testament: "NT" },
  { abbrev: "rm", name: "Romanos", chapters: 16, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1co", name: "1 Coríntios", chapters: 16, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2co", name: "2 Coríntios", chapters: 13, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "gl", name: "Gálatas", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "ef", name: "Efésios", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "fp", name: "Filipenses", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "cl", name: "Colossenses", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1ts", name: "1 Tessalonicenses", chapters: 5, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2ts", name: "2 Tessalonicenses", chapters: 3, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1tm", name: "1 Timóteo", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2tm", name: "2 Timóteo", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "tt", name: "Tito", chapters: 3, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "fm", name: "Filemom", chapters: 1, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "hb", name: "Hebreus", chapters: 13, author: "Desconhecido", group: "Cartas", testament: "NT" },
  { abbrev: "tg", name: "Tiago", chapters: 5, author: "Tiago", group: "Cartas", testament: "NT" },
  { abbrev: "1pe", name: "1 Pedro", chapters: 5, author: "Pedro", group: "Cartas", testament: "NT" },
  { abbrev: "2pe", name: "2 Pedro", chapters: 3, author: "Pedro", group: "Cartas", testament: "NT" },
  { abbrev: "1jo", name: "1 João", chapters: 5, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "2jo", name: "2 João", chapters: 1, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "3jo", name: "3 João", chapters: 1, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "jd", name: "Judas", chapters: 1, author: "Judas", group: "Cartas", testament: "NT" },
  { abbrev: "ap", name: "Apocalipse", chapters: 22, author: "João", group: "Revelação", testament: "NT" }
];

const OFFLINE_CHAPTERS = {
  // Gênesis 1 (NVI)
  "nvi-gn-1": [
    { number: 1, text: "No princípio criou Deus os céus e a terra." },
    { number: 2, text: "Era a terra sem forma e vazia; trevas cobriam a face do abismo, e o Espírito de Deus se movia sobre a face das águas." },
    { number: 3, text: "Disse Deus: \"Haja luz\", e houve luz." },
    { number: 4, text: "Viu Deus que a luz era boa, e separou a luz das trevas." },
    { number: 5, text: "Deus chamou à luz dia, e às trevas chamou noite. Passaram-se a tarde e a manhã; esse foi o primeiro dia." },
    { number: 6, text: "Depois disse Deus: \"Haja um firmamento no meio das águas para separar águas de águas\"." },
    { number: 7, text: "E assim aconteceu: Deus fez o firmamento e separou as águas que estavam debaixo do firmamento das que estavam por cima." },
    { number: 8, text: "Ao firmamento Deus chamou céu. Passaram-se a tarde e a manhã; esse foi o segundo dia." },
    { number: 9, text: "E disse Deus: \"Ajuntem-se as águas que estão debaixo do céu num só lugar, e apareça a parte seca\". E assim aconteceu." },
    { number: 10, text: "À parte seca Deus chamou terra, e ao conjunto das águas chamou mares. E viu Deus que isso era bom." },
    { number: 11, text: "Então disse Deus: \"Cubra-se a terra de vegetação: plantas que deem sementes e árvores frutíferas cuja fruta contenha semente, cada uma de acordo com a sua espécie, sobre a terra\". E assim aconteceu." },
    { number: 12, text: "A terra produziu vegetação: plantas que dão sementes de acordo com a sua espécie, e árvores que dão frutos cujas sementes estão neles, de acordo com a sua espécie. E viu Deus que isso era bom." },
    { number: 13, text: "Passaram-se a tarde e a manhã; esse foi o terceiro dia." },
    { number: 14, text: "Disse Deus: \"Haja luminares no firmamento do céu para separar o dia da noite. Sirvam eles como sinais para marcar estações, dias e anos,\"" },
    { number: 15, text: "\"e sirvam de luminares no firmamento do céu para iluminar a terra\". E assim aconteceu." },
    { number: 16, text: "Deus fez os dois grandes luminares: o luminar maior para governar o dia, e o luminar menor para governar a noite; fez também as estrelas." },
    { number: 17, text: "Deus os colocou no firmamento do céu para iluminar a terra," },
    { number: 18, text: "governar o dia e a noite, e separar a luz das trevas. E viu Deus que isso era bom." },
    { number: 19, text: "Passaram-se a tarde e a manhã; esse foi o quarto dia." },
    { number: 20, text: "Disse Deus: \"Encham-se as águas de seres vivos, e voem as aves sobre a terra, sob o firmamento do céu\"." },
    { number: 21, text: "Assim Deus criou os grandes animais aquáticos e os demais seres vivos que povoam as águas, de acordo com as suas espécies; e todas as aves, de acordo com as suas espécies. E viu Deus que isso era bom." },
    { number: 22, text: "Deus os abençoou, dizendo: \"Sejam férteis, multipliquem-se e encham as águas dos mares; e multipliquem-se as aves na terra\"." },
    { number: 23, text: "Passaram-se a tarde e a manhã; esse foi o quinto dia." },
    { number: 24, text: "E disse Deus: \"Produza a terra seres vivos de acordo com as suas espécies: rebanhos domésticos, animais selvagens e os demais seres vivos da terra, cada um de acordo com a sua espécie\". E assim aconteceu." },
    { number: 25, text: "Deus fez os animais selvagens de acordo com as suas espécies, os rebanhos domésticos de acordo com as suas espécies, e os demais seres vivos da terra de acordo com as suas espécies. E viu Deus que isso era bom." },
    { number: 26, text: "Então disse Deus: \"Façamos o homem à nossa imagem, conforme a nossa semelhança. Domine ele sobre os peixes do mar, sobre as aves do céu, sobre os animais grandes de toda a terra e sobre todos os pequenos animais que se movem rente ao chão\"." },
    { number: 27, text: "Criou Deus o homem à sua imagem, à imagem de Deus o criou; homem e mulher os criou." },
    { number: 28, text: "Deus os abençoou, e lhes disse: \"Sejam férteis e multipliquem-se! Encham e subjuguem a terra! Dominem sobre os peixes do mar, sobre as aves do céu e sobre todos os animais que se movem rente ao chão\"." },
    { number: 29, text: "Disse Deus ainda: \"Eis que lhes dou todas as plantas que dão semente em toda a terra, e todas as árvores que dão fruto com semente. Elas servirão de alimento para vocês.\"" },
    { number: 30, text: "\"E dou todos os vegetais como alimento a tudo o que tem em si fôlego de vida: a todos os animais da terra, a todas as aves do céu e a todos os répteis que se movem rente ao chão\". E assim aconteceu." },
    { number: 31, text: "E Deus viu tudo o que havia feito, e tudo havia ficado muito bom. Passaram-se a tarde e a manhã; esse foi o sexto dia." }
  ],

  // Gênesis 1 (ACF)
  "acf-gn-1": [
    { number: 1, text: "No princípio criou Deus os céus e a terra." },
    { number: 2, text: "E a terra era sem forma e vazia; e havia trevas sobre a face do abismo; e o Espírito de Deus se movia sobre a face das águas." },
    { number: 3, text: "E disse Deus: Haja luz; e houve luz." },
    { number: 4, text: "E viu Deus que era boa a luz; e fez Deus separação entre a luz e as trevas." },
    { number: 5, text: "E Deus chamou à luz Dia; e às trevas chamou Noite. E foi a tarde e a manhã, o dia primeiro." },
    { number: 6, text: "E disse Deus: Haja uma expansão no meio das águas, e haja separação entre águas e águas." },
    { number: 7, text: "E fez Deus a expansão, e fez separação entre as águas que estavam debaixo da expansão e as águas que estavam sobre a expansão; e assim foi." },
    { number: 8, text: "E chamou Deus à expansão Céu, e foi a tarde e a manhã, o dia segundo." },
    { number: 9, text: "E disse Deus: Ajuntem-se as águas debaixo dos céus num lugar; e apareça a porção seca; e assim foi." },
    { number: 10, text: "E chamou Deus à porção seca Terra; e ao ajuntamento das águas chamou Mares; e viu Deus que era bom." },
    { number: 11, text: "E disse Deus: Produza a terra erva verde, erva que dê semente, árvore frutífera que dê fruto segundo a sua espécie, cuja semente está nela sobre a terra; e assim foi." },
    { number: 12, text: "E a terra produziu erva, erva dando semente conforme a sua espécie, e árvore frutífera, cuja semente está nela conforme a sua espécie; e viu Deus que era bom." },
    { number: 13, text: "E foi a tarde e a manhã, o dia terceiro." },
    { number: 14, text: "E disse Deus: Haja luminares na expansão dos céus, para haver separação entre o dia e a noite; e sejam eles para sinais e para tempos determinados e para dias e anos." },
    { number: 15, text: "E sejam para luminares na expansão dos céus, para iluminar a terra; e assim foi." },
    { number: 16, text: "E fez Deus os dois grandes luminares: o luminar maior para governar o dia, e o luminar menor para governar a noite; e fez as estrelas." },
    { number: 17, text: "E Deus os pôs na expansão dos céus para iluminar a terra," },
    { number: 18, text: "E para governar o dia e a noite, e para fazer separação entre a luz e as trevas; e viu Deus que era bom." },
    { number: 19, text: "E foi a tarde e a manhã, o dia quarto." },
    { number: 20, text: "E disse Deus: Produzam as águas abundantemente répteis de alma vivente; e voem as aves sobre a terra sob a expansão dos céus." },
    { number: 21, text: "E Deus criou as grandes baleias, e todo o ser vivente que se move, que as águas abundantemente produziram conforme as suas espécies; e toda a ave de asas conforme a sua espécie; e viu Deus que era bom." },
    { number: 22, text: "E Deus os abençoou, dizendo: Frutificai e multiplicai-vos, e enchei as águas nos mares; e as aves se multipliquem na terra." },
    { number: 23, text: "E foi a tarde e a manhã, o dia quinto." },
    { number: 24, text: "E disse Deus: Produza a terra alma vivente conforme a sua espécie; gado, e répteis e feras da terra conforme a sua espécie; e assim foi." },
    { number: 25, text: "E fez Deus as feras da terra conforme a sua espécie, e o gado conforme a sua espécie, e todo o réptil da terra conforme a sua espécie; e viu Deus que era bom." },
    { number: 26, text: "E disse Deus: Façamos o homem à nossa imagem, conforme a nossa semelhança; e domine sobre os peixes do mar, e sobre as aves dos céus, e sobre o gado, e sobre toda a terra, e sobre todo o réptil que se move sobre a terra." },
    { number: 27, text: "E criou Deus o homem à sua imagem; à imagem de Deus o criou; homem e mulher os criou." },
    { number: 28, text: "E Deus os abençoou, e Deus lhes disse: Frutificai e multiplicai-vos, e enchei a terra, e sujeitai-a; e dominai sobre os peixes do mar e sobre as aves dos céus, e sobre todo o animal que se move sobre a terra." },
    { number: 29, text: "E disse Deus: Eis que vos tenho dado toda a erva que dê semente, que está sobre a face de toda a terra; e toda a árvore, em que há fruto que dê semente, ser-vos-á para mantimento." },
    { number: 30, text: "E a todo o animal da terra, e a toda a ave dos céus, e a todo o réptil da terra, em que há alma vivente, toda a erva verde lhes será para mantimento; e assim foi." },
    { number: 31, text: "E viu Deus tudo quanto tinha feito, e eis que era muito bom; e foi a tarde e a manhã, o dia sexto." }
  ],

  // Salmos 23 (NVI)
  "nvi-sl-23": [
    { number: 1, text: "O Senhor é o meu pastor; de nada terei falta." },
    { number: 2, text: "Em verdes pastagens me faz repousar e me conduz a águas tranquilas;" },
    { number: 3, text: "restaura-me o vigor. Guia-me nas veredas da justiça por amor do seu nome." },
    { number: 4, text: "Mesmo que eu ande pelo vale da sombra da morte, não temerei mal algum, porque tu estás comigo; a tua vara e o teu cajado me protegem." },
    { number: 5, text: "Preparas um banquete para mim na presença dos meus inimigos. Unges a minha cabeça com óleo; o meu cálice transborda." },
    { number: 6, text: "Sei que a bondade e a fidelidade me acompanharão todos os dias da minha vida, e voltarei à casa do Senhor pelos tempos infinitos." }
  ],

  // Salmos 23 (ACF)
  "acf-sl-23": [
    { number: 1, text: "O Senhor é o meu pastor, nada me faltará." },
    { number: 2, text: "Deitar-me faz em verdes pastos, guia-me mansamente a águas tranquilas." },
    { number: 3, text: "Refrigera a minha alma; guia-me pelas veredas da justiça, por amor do seu nome." },
    { number: 4, text: "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam." },
    { number: 5, text: "Preparas uma mesa perante mim na presença dos meus inimigos, unges a minha cabeça com óleo, o meu cálice transborda." },
    { number: 6, text: "Certamente que a bondade e a misericórdia me seguirão todos os dias da minha vida; e habitarei na casa do Senhor por longos dias." }
  ],

  // João 3 (NVI)
  "nvi-jo-3": [
    { number: 1, text: "Havia um fariseu chamado Nicodemos, uma autoridade entre os judeus." },
    { number: 2, text: "Ele veio a Jesus, à noite, e disse: \"Mestre, sabemos que ensinas da parte de Deus, pois ninguém pode realizar os sinais miraculosos que estás fazendo, se Deus não estiver com ele\"." },
    { number: 3, text: "Em resposta, Jesus declarou: \"Digo a verdade: Ninguém pode ver o Reino de Deus, se não nascer de novo\"." },
    { number: 4, text: "Perguntou Nicodemos: \"Como alguém pode nascer, sendo velho? É claro que não pode entrar pela segunda vez no ventre de sua mãe e nascer!\"" },
    { number: 5, text: "Respondeu Jesus: \"Digo a verdade: Ninguém pode entrar no Reino de Deus, se não nascer da água e do Espírito." },
    { number: 6, text: "O que nasce da carne é carne, mas o que nasce do Espírito é espírito." },
    { number: 7, text: "Não se surpreenda pelo fato de eu ter dito: É necessário que vocês nasçam de novo." },
    { number: 8, text: "O vento sopra onde quer. Você o escuta, mas não pode dizer de onde vem nem para onde vai. Assim acontece com todos os nascidos do Espírito\"." },
    { number: 9, text: "Perguntou Nicodemos: \"Como pode ser isso?\"" },
    { number: 10, text: "Disse Jesus: \"Você é mestre em Israel e não entende essas coisas?" },
    { number: 11, text: "Digo a verdade: Nós falamos do que conhecemos e testemunhamos do que vimos, mas vocês não aceitam o nosso testemunho." },
    { number: 12, text: "Se eu lhes falei de coisas terrenas e vocês não creram, como crerão se lhes falar de coisas celestiais?" },
    { number: 13, text: "Ninguém jamais subiu ao céu, a não ser aquele que veio do céu: o Filho do Homem." },
    { number: 14, text: "Como Moisés levantou a serpente no deserto, assim também é necessário que o Filho do Homem seja levantado," },
    { number: 15, text: "para que todo o que nele crer tenha a vida eterna." },
    { number: 16, text: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna." },
    { number: 17, text: "Pois Deus enviou o seu Filho ao mundo, não para condenar o mundo, mas para salvar o mundo por meio dele." },
    { number: 18, text: "Quem nele crê não é condenado, mas quem não crê já está condenado, por não crer no nome do Filho Unigênito de Deus." },
    { number: 19, text: "Este é o julgamento: a luz veio ao mundo, mas os homens amaram as trevas, e não a luz, porque as suas obras eram más." },
    { number: 20, text: "Quem pratica o mal odeia a luz e não se aproxima dela, temendo que as suas obras sejam manifestas." },
    { number: 21, text: "Mas quem pratica a verdade vem para a luz, para que se veja claramente que as suas obras são realizadas por intermédio de Deus\"." }
  ],

  // João 3 (ACF)
  "acf-jo-3": [
    { number: 1, text: "E havia entre os fariseus um homem, chamado Nicodemos, príncipe dos judeus." },
    { number: 2, text: "Este foi ter de noite com Jesus, e disse-lhe: Rabi, bem sabemos que és Mestre, vindo de Deus; porque ninguém pode fazer estes sinais que tu fazes, se Deus não for com ele." },
    { number: 3, text: "Jesus respondeu, e disse-lhe: Na verdade, na verdade te digo que aquele que não nascer de novo, não pode ver o reino de Deus." },
    { number: 4, text: "Disse-lhe Nicodemos: Como pode um homem nascer, sendo velho? Pode, porventura, entrar segunda vez no ventre de sua mãe, e nascer?" },
    { number: 5, text: "Jesus respondeu: Na verdade, na verdade te digo que aquele que não nascer da água e do Espírito, não pode entrar no reino de Deus." },
    { number: 6, text: "O que é nascido da carne é carne, e o que é nascido do Espírito é espírito." },
    { number: 7, text: "Não te maravilhes de te ter dito: Necessário vos é nascer de novo." },
    { number: 8, text: "O vento assopra onde quer, e ouves o seu ruído, mas não sabes de onde vem, nem para onde vai; assim é todo aquele que é nascido do Espírito." },
    { number: 9, text: "Nicodemos respondeu, e disse-lhe: Como pode ser isso?" },
    { number: 10, text: "Jesus respondeu, e disse-lhe: Tu és mestre de Israel, e não sabes isto?" },
    { number: 11, text: "Na verdade, na verdade te digo que nós dizemos o que sabemos, e testificamos o que vimos; e não aceitais o nosso testemunho." },
    { number: 12, text: "Se vos falei de coisas terrestres, e não crestes, como crereis, se vos falar das celestiais?" },
    { number: 13, text: "Ora, ninguém subiu ao céu, senão o que desceu do céu, o Filho do homem, que está no céu." },
    { number: 14, text: "E, como Moisés levantou a serpente no deserto, assim importa que o Filho do homem seja levantado;" },
    { number: 15, text: "Para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
    { number: 16, text: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
    { number: 17, text: "Porque Deus enviou o seu Filho ao mundo, não para condenar o mundo, mas para que o mundo seja salvo por ele." },
    { number: 18, text: "Quem crê nele não é condenado; mas quem não crê já está condenado, porquanto não crê no nome do unigênito Filho de Deus." },
    { number: 19, text: "E a condenação é esta: Que a luz veio ao mundo, e os homens amaram mais as trevas do que a luz, porque as suas obras eram más." },
    { number: 20, text: "Porque todo aquele que faz o mal odeia a luz, e não vem para a luz, para que as suas obras não sejam reprovadas." },
    { number: 21, text: "Mas quem pratica a verdade vem para a luz, a fim de que as suas obras sejam manifestas, porque são feitas em Deus." }
  ],

  // Provérbios 28 (NVI) - Igual a imagem anexada
  "nvi-pv-28": [
    { number: 1, text: "O ímpio foge, embora ninguém o persiga, mas os justos são corajosos como o leão." },
    { number: 2, text: "Os pecados de uma nação fazem mudar sempre os seus governantes, mas a ordem se mantém com um líder sábio e sensato." },
    { number: 3, text: "O pobre que se torna poderoso e oprime os pobres é como a tempestade súbita que destrói toda a plantação." },
    { number: 4, text: "Os que abandonam a lei elogiam os ímpios, mas os que obedecem à lei lutam contra eles." },
    { number: 5, text: "Os homens maus não entendem a justiça, mas os que buscam ao Senhor a entendem plenamente." },
    { number: 6, text: "Melhor é o pobre íntegro em sua conduta do que o rico perverso em seus caminhos." },
    { number: 7, text: "Quem obedece à lei é filho sábio, mas o companheiro dos glutões envergonha o pai." },
    { number: 8, text: "Quem aumenta sua riqueza com juros exorbitantes ajunta para algum outro, que será bondoso com os pobres." },
    { number: 9, text: "Se alguém se recusa a ouvir a lei, até suas orações serão detestáveis." },
    { number: 10, text: "Quem leva os justos pelo mau caminho cairá em sua própria armadilha, mas os íntegros receberão boa herança." },
    { number: 11, text: "O rico pode se julgar sábio, mas o pobre que tem discernimento o conhece a fundo." },
    { number: 12, text: "Quando os justos triunfam, há grande glória; mas, quando os ímpios sobem ao poder, o povo se esconde." },
    { number: 13, text: "Quem esconde os seus pecados não prospera, mas quem os confessa e os abandona encontra misericórdia." },
    { number: 14, text: "Como é feliz o homem constante no temor do Senhor! Mas quem endurece o coração cairá na desgraça." },
    { number: 15, text: "Como leão rugindo ou urso feroz é o ímpio que governa um povo necessitado." },
    { number: 16, text: "O governante sem discernimento aumenta a opressão, mas o que odeia a ganância desonesta prolongará os seus dias." },
    { number: 17, text: "O homem atormentado pela culpa de um homicídio fugirá até à sepultura; que ninguém o apoie!" },
    { number: 18, text: "Quem conduz uma vida íntegra será salvo, mas aquele cujos caminhos são tortuosos cairá de repente." },
    { number: 19, text: "Quem cultiva a sua terra terá fartura de alimento, mas quem vai atrás de fantasias se fartará de miséria." },
    { number: 20, text: "O homem fiel receberá muitas bênçãos, mas quem tem pressa de enriquecer não ficará sem castigo." },
    { number: 21, text: "Agir com parcialidade não é bom; o homem comete injustiça até por um pedaço de pão." },
    { number: 22, text: "O invejoso tem pressa de enriquecer, e não sabe que a miséria o aguarda." },
    { number: 23, text: "Quem repreende o próximo obterá no fim mais favor do que aquele que só lisonjeia com a língua." },
    { number: 24, text: "Quem rouba seu pai ou sua mãe e diz: \"Não é errado\", é parceiro de quem destrói." },
    { number: 25, text: "O ganancioso provoca brigas, mas quem confia no Senhor prosperará." },
    { number: 26, text: "Quem confia em si mesmo é insensato, mas quem anda segundo a sabedoria não corre perigo." },
    { number: 27, text: "Quem dá aos pobres não passará necessidade, mas quem fecha os olhos para eles sofrerá muitas maldições." },
    { number: 28, text: "Quando os ímpios sobem ao poder, o povo se esconde; mas, quando eles sucumbem, os justos florescem." }
  ],

  // Provérbios 28 (ACF)
  "acf-pv-28": [
    { number: 1, text: "Fugem os ímpios, sem que ninguém os persiga; mas os justos são ousados como um leão." },
    { number: 2, text: "Pela transgressão da terra muitos são os seus príncipes, mas por homem prudente e entendido a sua ordem se prolongará." },
    { number: 3, text: "O homem pobre que oprime os pobres é como chuva varredora, que não deixa mantimento." },
    { number: 4, text: "Os que deixam a lei louvam o ímpio; mas os que guardam a lei pelejam contra eles." },
    { number: 5, text: "Os homens maus não entendem o juízo, mas os que buscam ao Senhor entendem tudo." },
    { number: 6, text: "Melhor é o pobre que anda na sua integridade do que o de caminhos tortuosos, ainda que seja rico." },
    { number: 7, text: "O que guarda a lei é filho sábio, mas o companheiro dos comilões envergonha a seu pai." },
    { number: 8, text: "O que aumenta os seus bens com usura e ganância ajunta-os para o que se compadece do pobre." },
    { number: 9, text: "O que desvia os seus ouvidos de ouvir a lei, até a sua oração será abominável." },
    { number: 10, text: "O que leva os retos a desviar-se para um mau caminho, ele mesmo cairá na sua cova; mas os retos herdarão o bem." },
    { number: 11, text: "O homem rico é sábio aos seus próprios olhos, mas o pobre que é entendido o examina." },
    { number: 12, text: "Quando os justos se alegram, há grande glória; mas quando os ímpios sobem, os homens se escondem." },
    { number: 13, text: "O que encobre as suas transgressões nunca prosperará, mas o que as confessa e deixa, alcançará misericórdia." },
    { number: 14, text: "Bem-aventurado o homem que continuamente teme; mas o que endurece o seu coração cairá no mal." },
    { number: 15, text: "Como leão rugindo, e urso faminto, assim é o ímpio que domina sobre um povo pobre." },
    { number: 16, text: "O príncipe falto de inteligência multiplicará as opressões, mas o que odeia a avareza prolongará os seus dias." },
    { number: 17, text: "O homem carregado do sangue de qualquer pessoa fugirá até à cova; ninguém o detenha." },
    { number: 18, text: "O que anda sinceramente salvar-se-á, mas o perverso em seus caminhos cairá de um golpe." },
    { number: 19, text: "O que lavrar a sua terra fartar-se-á de pão, mas o que segue a ociosos se fartará de pobreza." },
    { number: 20, text: "O homem fiel abundará em bênçãos, mas o que se apressa a enriquecer não ficará sem castigo." },
    { number: 21, text: "Ter respeito a pessoas não é bom, porque até por um bocado de pão o homem prevaricará." },
    { number: 22, text: "Aquele que tem pressa de enriquecer é homem de olho mau, e não sabe que há de vir sobre ele a pobreza." },
    { number: 23, text: "O que repreende ao homem achará depois mais favor do que aquele que lisonjeia com a língua." },
    { number: 24, text: "O que rouba a seu pai ou a sua mãe, e diz: Não é transgressão, companheiro é do destruidor." },
    { number: 25, text: "O orgulhoso de coração levanta contendas, mas o que confia no Senhor prosperará." },
    { number: 26, text: "O que confia no seu próprio coração é insensato, mas o que anda sabiamente, alcançará salvação." },
    { number: 27, text: "O que dá ao pobre não terá necessidade, mas o que esconde os seus olhos terá muitas maldições." },
    { number: 28, text: "Quando os ímpios sobem, os homens se escondem, mas quando perecem, os justos se multiplicam." }
  ]
};
