// offline_data.js
// Dados estáticos da Bíblia para funcionamento offline e controle de rate limits

const BIBLE_BOOKS = [
  // Antigo Testamento
  { abbrev: "gn", name: "Gênesis", chapters: 50, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "ex", name: "Êxodo", chapters: 40, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "lv", name: "Levítico", chapters: 27, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "nm", name: "Números", chapters: 36, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "dt", name: "Deuteronômio", chapters: 34, author: "Moisés", group: "Pentateuco", testament: "VT" },
  { abbrev: "js", name: "Josué", chapters: 24, author: "Josué", group: "Históricos", testament: "VT" },
  { abbrev: "jz", name: "Juízes", chapters: 21, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "rt", name: "Rute", chapters: 4, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "1sm", name: "1 Samuel", chapters: 31, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "2sm", name: "2 Samuel", chapters: 24, author: "Samuel", group: "Históricos", testament: "VT" },
  { abbrev: "1rs", name: "1 Reis", chapters: 22, author: "Jeremias", group: "Históricos", testament: "VT" },
  { abbrev: "2rs", name: "2 Reis", chapters: 25, author: "Jeremias", group: "Históricos", testament: "VT" },
  { abbrev: "1cr", name: "1 Crônicas", chapters: 29, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "2cr", name: "2 Crônicas", chapters: 36, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "ed", name: "Esdras", chapters: 10, author: "Esdras", group: "Históricos", testament: "VT" },
  { abbrev: "ne", name: "Neemias", chapters: 13, author: "Neemias", group: "Históricos", testament: "VT" },
  { abbrev: "et", name: "Ester", chapters: 10, author: "Mardoqueu", group: "Históricos", testament: "VT" },
  { abbrev: "job", name: "Jó", chapters: 42, author: "Desconhecido", group: "Poéticos", testament: "VT" },
  { abbrev: "sl", name: "Salmos", chapters: 150, author: "Davi, Asafe, outros", group: "Poéticos", testament: "VT" },
  { abbrev: "pv", name: "Provérbios", chapters: 31, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "ec", name: "Eclesiastes", chapters: 12, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "ct", name: "Cânticos", chapters: 8, author: "Salomão", group: "Poéticos", testament: "VT" },
  { abbrev: "is", name: "Isaías", chapters: 66, author: "Isaías", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "jr", name: "Jeremias", chapters: 52, author: "Jeremias", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "lm", name: "Lamentações", chapters: 5, author: "Jeremias", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "ez", name: "Ezequiel", chapters: 48, author: "Ezequiel", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "dn", name: "Daniel", chapters: 12, author: "Daniel", group: "Profetas Maiores", testament: "VT" },
  { abbrev: "os", name: "Oseias", chapters: 14, author: "Oseias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "jl", name: "Joel", chapters: 3, author: "Joel", group: "Profetas Menores", testament: "VT" },
  { abbrev: "am", name: "Amós", chapters: 9, author: "Amós", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ob", name: "Obadias", chapters: 1, author: "Obadias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "jn", name: "Jonas", chapters: 4, author: "Jonas", group: "Profetas Menores", testament: "VT" },
  { abbrev: "mq", name: "Miqueias", chapters: 7, author: "Miqueias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "na", name: "Naum", chapters: 3, author: "Naum", group: "Profetas Menores", testament: "VT" },
  { abbrev: "hc", name: "Habacuque", chapters: 3, author: "Habacuque", group: "Profetas Menores", testament: "VT" },
  { abbrev: "sf", name: "Sofonias", chapters: 3, author: "Sofonias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ag", name: "Ageu", chapters: 2, author: "Ageu", group: "Profetas Menores", testament: "VT" },
  { abbrev: "zc", name: "Zacarias", chapters: 14, author: "Zacarias", group: "Profetas Menores", testament: "VT" },
  { abbrev: "ml", name: "Malaquias", chapters: 4, author: "Malaquias", group: "Profetas Menores", testament: "VT" },

  // Novo Testamento
  { abbrev: "mt", name: "Mateus", chapters: 28, author: "Mateus", group: "Evangelhos", testament: "NT" },
  { abbrev: "mc", name: "Marcos", chapters: 16, author: "Marcos", group: "Evangelhos", testament: "NT" },
  { abbrev: "lc", name: "Lucas", chapters: 24, author: "Lucas", group: "Evangelhos", testament: "NT" },
  { abbrev: "jo", name: "João", chapters: 21, author: "João", group: "Evangelhos", testament: "NT" },
  { abbrev: "at", name: "Atos", chapters: 28, author: "Lucas", group: "Histórico", testament: "NT" },
  { abbrev: "rm", name: "Romanos", chapters: 16, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1co", name: "1 Coríntios", chapters: 16, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2co", name: "2 Coríntios", chapters: 13, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "gl", name: "Gálatas", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "ef", name: "Efésios", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "fp", name: "Filipenses", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "cl", name: "Colossenses", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1ts", name: "1 Tessalonicenses", chapters: 5, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2ts", name: "2 Tessalonicenses", chapters: 3, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "1tm", name: "1 Timóteo", chapters: 6, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "2tm", name: "2 Timóteo", chapters: 4, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "tt", name: "Tito", chapters: 3, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "fm", name: "Filemom", chapters: 1, author: "Paulo", group: "Cartas", testament: "NT" },
  { abbrev: "hb", name: "Hebreus", chapters: 13, author: "Desconhecido", group: "Cartas", testament: "NT" },
  { abbrev: "tg", name: "Tiago", chapters: 5, author: "Tiago", group: "Cartas", testament: "NT" },
  { abbrev: "1pe", name: "1 Pedro", chapters: 5, author: "Pedro", group: "Cartas", testament: "NT" },
  { abbrev: "2pe", name: "2 Pedro", chapters: 3, author: "Pedro", group: "Cartas", testament: "NT" },
  { abbrev: "1jo", name: "1 João", chapters: 5, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "2jo", name: "2 João", chapters: 1, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "3jo", name: "3 João", chapters: 1, author: "João", group: "Cartas", testament: "NT" },
  { abbrev: "jd", name: "Judas", chapters: 1, author: "Judas", group: "Cartas", testament: "NT" },
  { abbrev: "ap", name: "Apocalipse", chapters: 22, author: "João", group: "Revelação", testament: "NT" }
];
